name: Build and deploy ASP.Net Core app to Azure Web App - myGuideMeApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release GUIDME/GUIDME.csproj

      - name: Publish Web App
        run: dotnet publish GUIDME/GUIDME.csproj -c Release -o ./publish_output

      - name: Verify published output
        run: |
          echo "Checking if publish_output exists..."
          ls -la ./publish_output # Kiểm tra file output có tồn tại không
          if [ -z "$(ls -A ./publish_output)" ]; then
            echo "❌ No files found in ./publish_output"
            exit 1
          fi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ./publish_output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: ./deploy_output # Tải file về thư mục deploy_output

      - name: Verify downloaded files
        run: |
          echo "Checking if deploy_output exists..."
          ls -la ./deploy_output
          if [ -z "$(ls -A ./deploy_output)" ]; then
            echo "❌ No files found in ./deploy_output"
            exit 1
          fi

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'myGuideMeApp'
          slot-name: 'Production'
          package: ./deploy_output
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_081124B7B52448FCBF6850C752CDF781 }}
